-- MySQL Script generated by MySQL Workbench
-- 06/21/17 16:17:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema newdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newdb` DEFAULT CHARACTER SET utf8 ;
USE `newdb` ;

-- -----------------------------------------------------
-- Table `newdb`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newdb`.`profile` (
  `id` VARCHAR(32) NOT NULL,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  `password` VARCHAR(90) NULL DEFAULT NULL,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `role` VARCHAR(45) NOT NULL,
  `company` VARCHAR(45) NULL DEFAULT NULL,
  `profilepic` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '	';


-- -----------------------------------------------------
-- Table `newdb`.`inbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newdb`.`inbox` (
  `messageid` VARCHAR(45) NOT NULL,
  `receiverId` VARCHAR(32) NOT NULL,
  `messagebody` LONGTEXT NULL DEFAULT NULL,
  `senderId` VARCHAR(32) NOT NULL,
  `datesent` DATE NULL DEFAULT NULL,
  `subject` MEDIUMTEXT NULL DEFAULT NULL,
  `files` MEDIUMTEXT NULL DEFAULT NULL,
  `receiverstatus` VARCHAR(15) NULL DEFAULT NULL,
  `senderstatus` VARCHAR(15) NULL DEFAULT NULL,
  `receiverread` VARCHAR(15) NULL DEFAULT NULL,
  `senderread` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`messageid`),
  INDEX `receiverid_idx` (`receiverId` ASC),
  INDEX `idforsender_idx` (`senderId` ASC),
  CONSTRAINT `idforreceiver`
    FOREIGN KEY (`receiverId`)
    REFERENCES `newdb`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idforsender`
    FOREIGN KEY (`senderId`)
    REFERENCES `newdb`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
